### ISSUE TITLE
How to cat the dataset in windows OS?

### ISSUE THREAD

**Issue by GanggangDong** [xingyifei2016/RotLieNet#1]
Hi, Dr. Xing, how to cat the dataset in windows OS. There is no cat command in windows. Thank you very much.

**Comment by xingyifei2016** [comment]
Hello Ganggang, I have not worked on a windows os for this project, so I can't give a definite answer, however solutions may be found online such as these. Thanks for asking!

https://stackoverflow.com/questions/34609650/how-to-split-file-in-windows-just-like-linux

**Comment by GanggangDong** [comment]
Thank you very much. I have achieved the cat job in winows.

**Comment by GanggangDong** [comment]
Hi, Dr Xing, there are 5 sets of data in each npy file. I find the last axis (data[4, :, :]) is the magnitude. What is the data of other 4 axis? Thank you very much.
